#!/usr/bin/env bash
# ABOUTME: Assembles bin/cs from its lib/*.sh fragments; edit lib/, never bin/cs.
# ABOUTME: Concatenates the numbered fragments in order, dropping each fragment's
# ABOUTME: own ABOUTME header so the built bin/cs keeps only lib/00-header.sh's.
# ABOUTME: Also writes hooks/cs-shared.sh from lib/02-shared.sh, the code hooks share with cs.
set -euo pipefail
cd "$(dirname "$0")"

LIB_DIR="lib"
OUT="bin/cs"
SHARED_SRC="$LIB_DIR/02-shared.sh"
SHARED_OUT="hooks/cs-shared.sh"

# The 2-digit numeric prefixes (00,05,10,...,99) give the fragments a total order
# under a plain lexical glob, so the assembled bin/cs is deterministic. Using the
# positional params keeps this portable to macOS's stock bash 3.2 (no mapfile).
set -- "$LIB_DIR"/[0-9]*-*.sh
if [ ! -e "$1" ]; then
    echo "error: no lib/*.sh fragments found in $LIB_DIR/" >&2
    exit 1
fi

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

first=1
for f in "$@"; do
    if [ "$first" = 1 ]; then
        # 00-header carries bin/cs's shebang and its single ABOUTME header.
        cat "$f" >> "$tmp"
        first=0
    else
        # Every other fragment documents itself with a leading ABOUTME block for
        # anyone reading lib/; strip that block (and its trailing blank) here so
        # the assembled tool has one header, not nineteen.
        awk 'BEGIN{lead=1}
             lead && /^# ABOUTME:/ {next}
             lead && /^[[:space:]]*$/ {lead=0; next}
             {lead=0; print}' "$f" >> "$tmp"
    fi
done

bash -n "$tmp"
chmod +x "$tmp"
mv "$tmp" "$OUT"
trap - EXIT
echo "Built $OUT from $# lib fragments ($(wc -l < "$OUT") lines)"

# The hooks cannot source lib/ (they run from ~/.claude/hooks/cs/, where only
# the hooks and their libraries are deployed), so the fragment they share with
# cs ships beside them as a library, byte-for-byte the lib/ file under a shebang.
# CI's build-sync job diffs this file too: it is generated, never hand-edited.
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
{
    echo '#!/usr/bin/env bash'
    echo "# Generated by build.sh from $SHARED_SRC. Edit that file, never this one."
    cat "$SHARED_SRC"
} > "$tmp"
bash -n "$tmp"
chmod +x "$tmp"
mv "$tmp" "$SHARED_OUT"
trap - EXIT
echo "Built $SHARED_OUT from $SHARED_SRC"
