#!/usr/bin/env bash
# Generated by build.sh from lib/02-shared.sh. Edit that file, never this one.
# ABOUTME: Actor identity and narrative-budget code that cs AND its hooks run. build.sh
# ABOUTME: folds this into bin/cs and writes it verbatim to hooks/cs-shared.sh for sourcing.

# Normalize an arbitrary identity string to a filesystem-safe slug.
_slugify() {
    printf '%s' "$1" \
        | tr '[:upper:]' '[:lower:]' \
        | sed 's/[^a-z0-9][^a-z0-9]*/-/g; s/^-//; s/-*$//'
}

# The raw identity driving a session, before slugging. Args: the session root
# (where git config is read) and its meta dir (where the pinned identity lives);
# either may be empty. Precedence: $CS_ACTOR > <meta>/local/identity > git
# user.email > git user.name > "unknown". if/elif/else, not three independent
# tests: a pinned identity file ends the search by EXISTING, so a blank pin
# resolves to "unknown" rather than falling through to git.
cs_actor_raw() {  # session_dir, meta_dir
    local sdir="${1:-}" meta="${2:-}" raw=""
    if [ -n "${CS_ACTOR:-}" ]; then
        raw="$CS_ACTOR"
    elif [ -n "$meta" ] && [ -f "$meta/local/identity" ]; then
        IFS= read -r raw < "$meta/local/identity" || true
    else
        local gitdir="${sdir:-.}"
        raw=$(git -C "$gitdir" config user.email 2>/dev/null || true)
        [ -z "$raw" ] && raw=$(git -C "$gitdir" config user.name 2>/dev/null || true)
    fi
    [ -z "$raw" ] && raw="unknown"
    printf '%s\n' "$raw"
}

# Resolve the current actor as a slug. With a session_dir arg, resolve the
# pinned identity and git config from that dir (callers may run before
# CLAUDE_SESSION_META_DIR is exported). Without, use env + cwd.
cs_actor_slug() {
    local sdir="${1:-}" meta=""
    if [ -n "$sdir" ]; then
        meta="$sdir/.cs"
    else
        meta="${CLAUDE_SESSION_META_DIR:-}"
    fi
    _slugify "$(cs_actor_raw "$sdir" "$meta")"
}

# 224 KiB budget, 112 KiB tail. The ceiling is the Read tool's: it refuses a
# file over 256 KiB, and the resume reads the live narrative in one call, so a
# file past that size cannot be read in full at all. The budget sits under the
# ceiling with room for the appends made while the over-budget warning is on
# screen and before anyone rotates. The tail is what a resume actually costs;
# sections run about 2 KB and an active day produces 60-odd of them, so 112 KiB
# is most of a day. The 2:1 ratio keeps rotation infrequent: a full tail's
# worth must accumulate again before the next one.
CS_NARRATIVE_MAX_DEFAULT=229376
CS_NARRATIVE_KEEP_DEFAULT=114688

# A positive integer override, else the default. Empty, non-numeric and zero
# in any spelling (0, 00) all fall back: a zero budget would rotate on every
# run. The zero check runs on the number, not the text, and the number is
# decimal: a leading zero would reach the callers' arithmetic as an octal
# literal, and `08` aborts it.
_narrative_budget() {  # value, default
    local n
    case "${1:-}" in ''|*[!0-9]*) echo "$2"; return;; esac
    n=$((10#$1))
    if [ "$n" -gt 0 ]; then echo "$n"; else echo "$2"; fi
}

# The finished-turn notification's poster. The installer assembles cs.app, a
# copy of terminal-notifier.app whose icon is the cs owl, because macOS shows
# a notification with its SENDER's icon and nothing a poster passes
# (-appIcon, -contentImage) changes that. Groups are per sender app too, so
# the post and the removes must all go through one binary: the bundle's when
# it is installed, else terminal-notifier from PATH, else nothing (rc 1).
cs_notifier_app() {
    printf '%s' "${XDG_DATA_HOME:-$HOME/.local/share}/cs/cs.app"
}
cs_notifier_bin() {
    local app
    app="$(cs_notifier_app)/Contents/MacOS/terminal-notifier"
    if [ -x "$app" ]; then
        printf '%s' "$app"
        return 0
    fi
    command -v terminal-notifier 2>/dev/null
}

# The binary a bundle is assembled from: the terminal-notifier.app Homebrew
# keeps beside the bin/ wrapper that PATH resolves to (that wrapper is a
# 124-byte script, not the poster), or the resolved PATH entry itself in any
# other layout. install.sh resolves the source app the same way; the doctor
# hashes this to tell a bundle a brew upgrade left behind. rc 1 when there
# is no terminal-notifier on PATH.
cs_notifier_source_bin() {
    local bin real app
    bin=$(command -v terminal-notifier 2>/dev/null) || return 1
    real=$(readlink -f "$bin" 2>/dev/null) || real="$bin"
    app="$(dirname "$real")/../terminal-notifier.app/Contents/MacOS/terminal-notifier"
    if [ -x "$app" ]; then
        printf '%s' "$app"
    else
        printf '%s' "$real"
    fi
}
